### ISSUE TITLE
Can't find  "same_event_doc_pair.no_cd.json". I have used 'git lfs clone' to clone the project.

### ISSUE THREAD

**Issue by briny-fish** [BangLiu/ArticlePairMatching#24]
Traceback (most recent call last):
  File "main.py", line 102, in <module>
    labels, idx_train, idx_val, idx_test = load_graph_data(path, word_to_ix, MAX_LEN, args.num_data)
  File "/content/ArticlePairMatching/src/models/CCIG/loader.py", line 81, in load_graph_data
    fin = open(path, "r", encoding="utf-8")
FileNotFoundError: [Errno 2] No such file or directory: '../../../data/processed/event-story-cluster/same_event_doc_pair.no_cd.json'

**Comment by briny-fish** [comment]
Sorry,  I forgot to run feature_exactor.py
