### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by Akakaala** [BangLiu/ArticlePairMatching#35]
WARNING **: 01:45:59.539: Failed to load shared library 'libgdk-3.so.0' referenced by the typelib: libXcursor.so.1: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "feature_extractor.py", line 8, in <module>
    from graph_tool.all import *
  File "/opt/conda/lib/python3.6/site-packages/graph_tool/all.py", line 34, in <module>
    from graph_tool.draw import *
  File "/opt/conda/lib/python3.6/site-packages/graph_tool/draw/__init__.py", line 835, in <module>
    from . cairo_draw import graph_draw, cairo_draw, \
  File "/opt/conda/lib/python3.6/site-packages/graph_tool/draw/cairo_draw.py", line 1496, in <module>
    from gi.repository import Gtk, Gdk, GdkPixbuf
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/opt/conda/lib/python3.6/site-packages/gi/importer.py", line 144, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/opt/conda/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/opt/conda/lib/python3.6/site-packages/gi/importer.py", line 145, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/opt/conda/lib/python3.6/site-packages/gi/overrides/__init__.py", line 118, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "/opt/conda/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/conda/lib/python3.6/site-packages/gi/overrides/Gdk.py", line 83, in <module>
    Color = override(Color)
  File "/opt/conda/lib/python3.6/site-packages/gi/overrides/__init__.py", line 195, in override
    assert g_type != TYPE_NONE
AssertionError

**Comment by Akakaala** [comment]
一直卡在这个问题 环境graph-tool=2.43

**Comment by Akakaala** [comment]
有人遇到这个问题嘛！求解答谢谢

**Comment by Akakaala** [comment]
apt install libxcursor1
解决
