### ISSUE TITLE
KeyError: 'content1'

### ISSUE THREAD

**Issue by tingwt** [BangLiu/ArticlePairMatching#5]

**Comment by tingwt** [comment]
sorry,  I 

> 0
> graph 0
> parallel extract graph features
> 0
> graph 0
> parallel extract graph features
> multiprocessing.pool.RemoteTraceback:
> """
> Traceback (most recent call last):
> File "/home/wting/anaconda3/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3124, in get_value
> return libindex.get_value_box(s, key)
> File "pandas/_libs/index.pyx", line 55, in pandas._libs.index.get_value_box
> File "pandas/_libs/index.pyx", line 63, in pandas._libs.index.get_value_box
> TypeError: 'str' object cannot be interpreted as an integer
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
> File "/home/wting/anaconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
> result = (True, func(*args, **kwds))
> File "/home/wting/anaconda3/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
> return list(map(*args))
> File "feature_extractor.py", line 225, in text_pair2graph_worker
> text1 = df.loc[i][col_text1]
> File "/home/wting/anaconda3/lib/python3.7/site-packages/pandas/core/series.py", line 767, in getitem
> result = self.index.get_value(self, key)
> File "/home/wting/anaconda3/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3132, in get_value
> raise e1
> File "/home/wting/anaconda3/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3118, in get_value
> tz=getattr(series.dtype, 'tz', None))
> File "pandas/_libs/index.pyx", line 106, in pandas._libs.index.IndexEngine.get_value
> File "pandas/_libs/index.pyx", line 114, in pandas._libs.index.IndexEngine.get_value
> File "pandas/_libs/index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
> File "pandas/_libs/hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
> File "pandas/_libs/hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
> KeyError: 'content1'
> """
> The above exception was the direct cause of the following exception:
> Traceback (most recent call last):
> File "feature_extractor.py", line 451, in 
> betweenness_threshold_coef=1.0, max_c_size=6, min_c_size=2)
> File "feature_extractor.py", line 420, in dataset2featurefile
> betweenness_threshold_coef, max_c_size, min_c_size)
> File "feature_extractor.py", line 301, in extract_align_graphs_from_docpair_data
> gs = pool.map(partial_worker, extract_range)
> File "/home/wting/anaconda3/lib/python3.7/multiprocessing/pool.py", line 268, in map
> return self._map_async(func, iterable, mapstar, chunksize).get()
> File "/home/wting/anaconda3/lib/python3.7/multiprocessing/pool.py", line 657, in get
> raise self._value
> KeyError: 'content1'
> When I run the features.py, I meet the keyerror problem, how to sovle the problem
> thanks

sorry
